version = '2'

[linters]
default = 'all'
disable = [
  'depguard',
  'ireturn',
  'musttag',
  'nlreturn',
  'sqlclosecheck'
]

[linters.settings]
[linters.settings.tagliatelle]
[linters.settings.tagliatelle.case]
[linters.settings.tagliatelle.case.rules]
envconfig = 'upperSnake'
json = 'snake'

[linters.settings.varnamelen]
ignore-names = [
  'rx',
  'tx',
  'db',
  'ok',
  'mw',
  'gw',
  'rt',
  'id',
  'mx'
]
ignore-decls = [
  'w http.ResponseWriter',
  'r *http.Request',
  'g *Gateway'
]

[linters.settings.wsl]
allow-trailing-comment = true
allow-cuddle-declarations = true

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'gosec'
]
text = 'G601:'

[[linters.exclusions.rules]]
linters = [
  'errcheck'
]
text = 'viper.Bind'

[[linters.exclusions.rules]]
linters = [
  'mnd'
]
source = 'cobra.MinimumNArgs'

[[linters.exclusions.rules]]
linters = [
  'gochecknoglobals',
  'gochecknoinits'
]
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = [
  'err113',
  'wrapcheck'
]
path = 'cmd/.*\.go'

[[linters.exclusions.rules]]
linters = [
  'forbidigo',
  'godot',
  'gosec',
  'varnamelen'
]
path = 'internal/.*\.go'

[severity]
default = 'warn'

[[severity.rules]]
linters = [
  'exhaustive',
  'exhaustruct',
  'godox'
]
severity = 'info'

[formatters]
enable = [
  'gci',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
