name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: "*/*.sum"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglfw3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev pkg-config

      - name: Download Go modules
        run: go mod download

      - name: Lint code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: -D exhaustruct -D exhaustive -D godox --timeout 5m
